# Generated by Django 2.0.4 on 2018-04-29 05:57

from django.db import migrations, models
import tips.models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'verbose_name_plural': 'Tips'},
        ),
        migrations.AlterField(
            model_name='tips',
            name='hoursFile',
            field=models.FileField(upload_to=tips.models.getUploadFileName),
        ),
    ]
