# Generated by Django 2.0.4 on 2018-04-30 22:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20180429_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tips',
            name='body',
        ),
        migrations.AddField(
            model_name='tips',
            name='monCashTips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tips',
            name='monCredTips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tips',
            name='tuesCashTips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tips',
            name='tuesCredTips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
