# Generated by Django 2.0.4 on 2018-04-30 23:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20180430_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='hoursFile',
            new_name='hours_File',
        ),
        migrations.RenameField(
            model_name='tips',
            old_name='monCashTips',
            new_name='w7_Mon_Cash_Tips',
        ),
        migrations.RenameField(
            model_name='tips',
            old_name='monCredTips',
            new_name='w7_Mon_Cred_Tips',
        ),
        migrations.AddField(
            model_name='tips',
            name='wee_Mon_Cash_Tips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='tips',
            name='wee_Mon_Cred_Tips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
