# Generated by Django 2.0.4 on 2018-05-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_auto_20180507_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='day_id',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
