# Generated by Django 2.0.4 on 2018-05-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_auto_20180510_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='employees',
            field=models.ManyToManyField(to='tips.Employee'),
        ),
    ]
