# Generated by Django 2.0.4 on 2018-05-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_auto_20180512_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='total_hours',
        ),
    ]
